---
:brisket_url: 'https://www.goldbelly.com/franklin-barbecue/whole-brisket-texas-bbq-sauce'
:alert_username: 'gmail_username@gmail.com'
:alert_pword: 'gmail_password'
:alert_number: 'verizon_10_digit_phone_number@vtext.com'
